sudo: required
dist: trusty
before_install:
    - sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended latexmk texlive-lang-german texlive-doc-de pgf texlive-font-utils zip inkscape texlive-math-extra graphviz make git openssh-client figlet
      
addons:
  ssh_known_hosts: aul12.me
  #sonarcloud:
  #  organization: "sopra-team-10" # the key of the org you chose at step #3
  #  token:
  #    secure: $SONAR_TOKEN # encrypted value of your token

script:
    #- sonar-scanner
    - mkdir output
    - cd Meilenstein01
    - make
    - mv main.pdf ../output/Meilenstein01.pdf
    - cd ..

notifications:
    slack: soprateam10:wlcgvL7tR63frGyGP4BCuqNj
    
deploy:
    provider: script
    skip-cleanup: true
    keep-history: true
    script: sh deploy.sh $TRAVIS_COMMIT
    all_branches: true
